<?= $this->extend('layouts/public') ?>

<?= $this->section('title') ?><?= $page_title ?> - Perpustakaan Nasional RI<?= $this->endSection() ?>

<?= $this->section('description') ?><?= $meta_description ?><?= $this->endSection() ?>

<?= $this->section('keywords') ?>kerja sama akan berakhir, masa berlaku kerjasama, perpanjangan kerjasama, perpustakaan nasional<?= $this->endSection() ?>

<?= $this->section('styles') ?>
<link href="<?= base_url('css/public.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/kerjasama/akan_berakhir.css') ?>" rel="stylesheet">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<?= $this->endSection() ?>

<?= $this->section('content') ?>

<!-- Main Content Wrapper -->
<div class="akan-berakhir-wrapper">
    <div class="container">
        
        <!-- Page Header -->
        <div class="akan-berakhir-page-header" data-aos="fade-down">
            <div class="akan-berakhir-header-content">
                <h1 class="akan-berakhir-page-title">Kerja Sama yang Akan Berakhir</h1>
                <div class="akan-berakhir-breadcrumb">
                    <span>Kerja Sama</span>
                    <span class="separator">/</span>
                    <span class="current">Kerja Sama yang Akan Berakhir</span>
                </div>
            </div>
        </div>

        <!-- Search Section -->
        <div class="akan-berakhir-search-section" data-aos="fade-up" data-aos-delay="200">
            <div class="akan-berakhir-search-container">
                <div class="akan-berakhir-search-box">
                    <input type="text" 
                           class="akan-berakhir-search-input"
                           id="searchInput" 
                           placeholder="Cari Data"
                           autocomplete="off">
                    <button class="akan-berakhir-search-btn" type="button" id="searchBtn">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Data Table Section -->
        <div class="akan-berakhir-table-section" data-aos="fade-up" data-aos-delay="300">
            <div class="akan-berakhir-table-container">
                <table class="akan-berakhir-table" id="akanBerakhirTable">
                    <thead>
                        <tr>
                            <th class="akan-berakhir-col-partner">Nama Mitra</th>
                            <th class="akan-berakhir-col-scope">Ruang Lingkup</th>
                            <th class="akan-berakhir-col-start">Tanggal Mulai</th>
                            <th class="akan-berakhir-col-end">Tanggal Berakhir</th>
                        </tr>
                    </thead>
                    <tbody id="akanBerakhirTableBody">
                        <!-- Data will be loaded here -->
                    </tbody>
                </table>
                
                <!-- Loading State -->
                <div class="akan-berakhir-loading-state" id="loadingState" style="display: none;">
                    <div class="akan-berakhir-loading-spinner">
                        <i class="fas fa-spinner fa-spin"></i>
                    </div>
                    <p>Memuat data kerja sama yang akan berakhir...</p>
                </div>
                
                <!-- Empty State -->
                <div class="akan-berakhir-empty-state" id="emptyState" style="display: none;">
                    <div class="akan-berakhir-empty-icon">
                        <i class="fas fa-calendar-times"></i>
                    </div>
                    <h4>Tidak ada kerja sama yang akan berakhir</h4>
                    <p>Semua kerja sama masih dalam masa berlaku yang aman</p>
                </div>
            </div>
        </div>

        <!-- Pagination Section -->
        <div class="akan-berakhir-pagination-section" data-aos="fade-up" data-aos-delay="400">
            <nav class="pagination-nav" aria-label="Navigation halaman">
                <ul class="akan-berakhir-pagination" id="paginationList">
                    <!-- Pagination will be generated by JavaScript -->
                </ul>
            </nav>
        </div>

    </div>
</div>

<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    // Initialize AOS
    AOS.init({
        duration: 800,
        easing: 'ease-in-out',
        once: true,
        offset: 100
    });
    
    // Pass PHP data to JavaScript
    window.akanBerakhirInitialData = <?= json_encode($akan_berakhir_data ?? []) ?>;
    window.akanBerakhirStats = <?= json_encode($akan_berakhir_stats ?? []) ?>;
    window.filterOptions = <?= json_encode($filter_options ?? []) ?>;
</script>
<script src="<?= base_url('js/public/kerjasama/akan_berakhir.js') ?>"></script>
<?= $this->endSection() ?>