<?= $this->extend('layouts/public') ?>

<?= $this->section('title') ?><?= $page_title ?> - Perpustakaan Nasional RI<?= $this->endSection() ?>

<?= $this->section('description') ?><?= $meta_description ?><?= $this->endSection() ?>

<?= $this->section('keywords') ?>data kerja sama, mou, moa, pks, perpustakaan nasional, mitra, kerjasama perpustakaan, institusi<?= $this->endSection() ?>

<?= $this->section('styles') ?>
<link href="<?= base_url('css/public.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/kerjasama/data.css') ?>" rel="stylesheet">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<?= $this->endSection() ?>

<?= $this->section('content') ?>

<!-- Main Content Wrapper -->
<div class="kerjasama-data-wrapper">
    <div class="container">
        
        <!-- Page Header -->
        <div class="kerjasama-page-header" data-aos="fade-down">
            <div class="kerjasama-header-content">
                <h1 class="kerjasama-page-title">Data Kerja Sama</h1>
                <div class="kerjasama-breadcrumb">
                    <span>Kerja Sama</span>
                    <span class="separator">/</span>
                    <span class="current">Data Kerja Sama</span>
                </div>
            </div>
        </div>

        <!-- Search Section -->
        <div class="kerjasama-search-section" data-aos="fade-up" data-aos-delay="200">
            <div class="kerjasama-search-container">
                <div class="kerjasama-search-box">
                    <input type="text" 
                           class="kerjasama-search-input"
                           id="searchInput" 
                           placeholder="Cari Data"
                           autocomplete="off">
                    <button class="kerjasama-search-btn" type="button" id="searchBtn">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Data Table Section -->
        <div class="kerjasama-table-section" data-aos="fade-up" data-aos-delay="300">
            <!-- Shared Table Component -->
            <?= view('components/kerjasama_table', [
                'data' => $cooperation_data ?? [
                    [
                        'id' => 1,
                        'nama_mitra' => 'Fulan',
                        'lingkup' => 'Pelestarian warisan dokumenter budaya Nusantara dan pengembangan sistem informasi perpustakaan digital untuk mendukung akses informasi yang lebih luas',
                        'tanggal_mulai' => '14/08/2025',
                        'tanggal_berakhir' => '14/08/2026'
                    ],
                    [
                        'id' => 2,
                        'nama_mitra' => 'Fulana',
                        'lingkup' => 'Pelestarian warisan dokumenter budaya Nusantara dan digitalisasi koleksi naskah kuno untuk kepentingan penelitian dan edukasi',
                        'tanggal_mulai' => '13/08/2025',
                        'tanggal_berakhir' => '13/08/2026'
                    ]
                ],
                'show_checkbox' => false,
                'show_actions' => false,
                'table_class' => 'kerjasama-table',
                'thead_class' => '',
                'container_class' => 'kerjasama-table-container',
                'table_id' => 'cooperationTable',
                'tbody_id' => 'cooperationTableBody',
                'col_partner_class' => 'kerjasama-col-partner',
                'col_scope_class' => 'kerjasama-col-scope',
                'col_start_class' => 'kerjasama-col-start',
                'col_end_class' => 'kerjasama-col-end',
                'scope_label' => 'Ruang Lingkup',
                'truncate_scope' => false,
                'show_loading' => true,
                'loading_class' => 'kerjasama-loading-state',
                'loading_id' => 'loadingState',
                'loading_spinner_class' => 'kerjasama-loading-spinner',
                'loading_text' => 'Memuat data kerja sama...',
                'show_empty' => true,
                'empty_class' => 'kerjasama-empty-state',
                'empty_id' => 'emptyState',
                'empty_icon_class' => 'kerjasama-empty-icon',
                'empty_icon' => 'search',
                'empty_title_level' => '4',
                'empty_title' => 'Tidak ada data ditemukan',
                'empty_text' => 'Coba ubah kriteria pencarian Anda'
            ]) ?>
        </div>
        
        <!-- Pagination Section -->
        <div class="kerjasama-pagination-section" data-aos="fade-up" data-aos-delay="400">
            <nav class="pagination-nav" aria-label="Navigation halaman">
                <ul class="kerjasama-pagination" id="paginationList">
                    <!-- Pagination will be generated by JavaScript -->
                </ul>
            </nav>
        </div>

    </div>
</div>

<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    // Initialize AOS
    AOS.init({
        duration: 800,
        easing: 'ease-in-out',
        once: true,
        offset: 100
    });
    
    // Pass PHP data to JavaScript
    window.cooperationInitialData = <?= json_encode($cooperation_data) ?>;
    window.cooperationStats = <?= json_encode($cooperation_stats) ?>;
    window.filterOptions = <?= json_encode($filter_options) ?>;
    
    // Search functionality for public table
    document.getElementById('searchInput').addEventListener('keyup', function() {
        const searchTerm = this.value.toLowerCase();
        const tableRows = document.querySelectorAll('#cooperationTableBody tr');
        
        tableRows.forEach(row => {
            const namaMitra = row.cells[0].textContent.toLowerCase();
            const lingkup = row.cells[1].textContent.toLowerCase();
            
            if (namaMitra.includes(searchTerm) || lingkup.includes(searchTerm)) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
        
        // Show/hide empty state
        const visibleRows = document.querySelectorAll('#cooperationTableBody tr[style=""], #cooperationTableBody tr:not([style])');
        const emptyState = document.getElementById('emptyState');
        if (visibleRows.length === 0 && searchTerm.length > 0) {
            emptyState.style.display = 'block';
        } else {
            emptyState.style.display = 'none';
        }
    });
</script>
<script src="<?= base_url('js/public/kerjasama/data.js') ?>"></script>
<?= $this->endSection() ?>