<?= $this->extend('layouts/public') ?>

<?= $this->section('title') ?><?= $page_title ?> - Perpustakaan Nasional RI<?= $this->endSection() ?>

<?= $this->section('description') ?><?= $meta_description ?><?= $this->endSection() ?>

<?= $this->section('keywords') ?>data kerja sama, mou, moa, pks, perpustakaan nasional, mitra, kerjasama perpustakaan, institusi<?= $this->endSection() ?>

<?= $this->section('styles') ?>
<link href="<?= base_url('css/public.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/navigation.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/kerjasama_data.css') ?>" rel="stylesheet">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<?= $this->endSection() ?>

<?= $this->section('content') ?>

<!-- Include Navigation Component -->
<?= $this->include('layouts/components/public_navigation') ?>

<!-- Main Content Wrapper -->
<div class="kerjasama-data-wrapper">
    <div class="container">
        
        <!-- Page Header -->
        <div class="page-header-section" data-aos="fade-down">
            <div class="header-content">
                <h1 class="page-title">Data Kerja Sama</h1>
                <div class="breadcrumb-nav">
                    <span>Kerja Sama</span>
                    <span class="separator">/</span>
                    <span class="current">Data Kerja Sama</span>
                </div>
            </div>
        </div>

        <!-- Search Section -->
        <div class="search-section" data-aos="fade-up" data-aos-delay="200">
            <div class="search-container">
                <div class="search-box">
                    <input type="text" 
                           class="search-input" 
                           id="searchInput" 
                           placeholder="Cari Data"
                           autocomplete="off">
                    <button class="search-btn" type="button" id="searchBtn">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Data Table Section -->
        <div class="data-table-section" data-aos="fade-up" data-aos-delay="300">
            <div class="table-container">
                <table class="cooperation-table" id="cooperationTable">
                    <thead>
                        <tr>
                            <th class="col-partner">Nama Mitra</th>
                            <th class="col-scope">Ruang Lingkup</th>
                            <th class="col-start">Tanggal Mulai</th>
                            <th class="col-end">Tanggal Berakhir</th>
                        </tr>
                    </thead>
                    <tbody id="cooperationTableBody">
                        <!-- Data will be loaded here -->
                    </tbody>
                </table>
                
                <!-- Loading State -->
                <div class="loading-state" id="loadingState" style="display: none;">
                    <div class="loading-spinner">
                        <i class="fas fa-spinner fa-spin"></i>
                    </div>
                    <p>Memuat data kerja sama...</p>
                </div>
                
                <!-- Empty State -->
                <div class="empty-state" id="emptyState" style="display: none;">
                    <div class="empty-icon">
                        <i class="fas fa-search"></i>
                    </div>
                    <h4>Tidak ada data ditemukan</h4>
                    <p>Coba ubah kriteria pencarian Anda</p>
                </div>
            </div>
        </div>

        <!-- Pagination Section -->
        <div class="pagination-section" data-aos="fade-up" data-aos-delay="400">
            <nav class="pagination-nav" aria-label="Navigation halaman">
                <ul class="pagination" id="paginationList">
                    <!-- Pagination will be generated by JavaScript -->
                </ul>
            </nav>
        </div>

    </div>
</div>

<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    // Initialize AOS
    AOS.init({
        duration: 800,
        easing: 'ease-in-out',
        once: true,
        offset: 100
    });
    
    // Pass PHP data to JavaScript
    window.cooperationInitialData = <?= json_encode($cooperation_data) ?>;
    window.cooperationStats = <?= json_encode($cooperation_stats) ?>;
    window.filterOptions = <?= json_encode($filter_options) ?>;
</script>
<script src="<?= base_url('js/public/kerjasama_data.js') ?>"></script>
<?= $this->endSection() ?>