<?= $this->extend('layouts/public') ?>

<?= $this->section('title') ?><?= $page_title ?> - Perpustakaan Nasional RI<?= $this->endSection() ?>

<?= $this->section('description') ?><?= $meta_description ?><?= $this->endSection() ?>

<?= $this->section('keywords') ?>data kerja sama, mou, moa, pks, perpustakaan nasional, mitra, kerjasama perpustakaan, institusi<?= $this->endSection() ?>

<?= $this->section('styles') ?>
<link href="<?= base_url('css/public.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/kerjasama/data.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/components/filter.css') ?>" rel="stylesheet">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<?= $this->endSection() ?>

<?= $this->section('content') ?>

<!-- Main Content Wrappers -->
<div class="kerjasama-data-wrapper">
    <div class="container">
        
        <!-- Page Header -->
        <div class="kerjasama-page-header" data-aos="fade-down">
            <div class="kerjasama-header-content">
                <h1 class="kerjasama-page-title">Data Kerja Sama</h1>
                <div class="kerjasama-breadcrumb">
                    <span>Kerja Sama</span>
                    <span class="separator">/</span>
                    <span class="current">Data Kerja Sama</span>
                </div>
            </div>
        </div>

        <!-- Search Section -->
        <div class="kerjasama-search-section" data-aos="fade-up" data-aos-delay="200">
            <div class="kerjasama-search-container">
                <div class="kerjasama-search-box">
                    <input type="text" 
                           class="kerjasama-search-input"
                           id="searchInput" 
                           placeholder="Cari Data"
                           autocomplete="off">
                    <button class="kerjasama-search-btn" type="button" id="searchBtn">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Data Table Section -->
        <div class="kerjasama-table-section" data-aos="fade-up" data-aos-delay="300">
                        <div class="kerjasama-table-container">
                <table class="kerjasama-table" id="cooperationTable">
                    <thead>
                        <tr>
                            <th class="kerjasama-col-partner">Nama Mitra</th>
                            <th class="kerjasama-col-scope">Ruang Lingkup</th>
                            <th class="kerjasama-col-start">Tanggal Mulai</th>
                            <th class="kerjasama-col-end">Tanggal Berakhir</th>
                        </tr>
                    </thead>
                    <tbody id="cooperationTableBody">
                        <!-- Data will be loaded here -->
                    </tbody>
                </table>
                
                <!-- Loading State -->
                <div class="kerjasama-loading-state" id="loadingState" style="display: none;">
                    <div class="kerjasama-loading-spinner">
                        <i class="fas fa-spinner fa-spin"></i>
                    </div>
                    <p>Memuat data kerja sama...</p>
                </div>
                
                <!-- Empty State -->
                <div class="kerjasama-empty-state" id="emptyState" style="display: none;">
                    <div class="kerjasama-empty-icon">
                        <i class="fas fa-search"></i>
                    </div>
                    <h4>Tidak ada data ditemukan</h4>
                    <p>Coba ubah kriteria pencarian Anda</p>
                </div>
            </div>
        </div>
        
        <!-- Pagination Section -->
        <div class="kerjasama-pagination-section" data-aos="fade-up" data-aos-delay="400">
            <nav class="pagination-nav" aria-label="Navigation halaman">
                <ul class="kerjasama-pagination" id="paginationList">
                    <!-- Pagination will be generated by JavaScript -->
                </ul>
            </nav>
        </div>

    </div>
</div>

<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    // Initialize AOS
    AOS.init({
        duration: 800,
        easing: 'ease-in-out',
        once: true,
        offset: 100
    });
    
    // Pass PHP data to JavaScript
    window.cooperationInitialData = <?= json_encode($cooperation_data) ?>;
    window.cooperationStats = <?= json_encode($cooperation_stats) ?>;
    window.filterOptions = <?= json_encode($filter_options) ?>;
    
    // Format dates for display
    window.formatDate = function(dateString) {
        const date = new Date(dateString);
        return date.toLocaleDateString('id-ID', {
            day: '2-digit',
            month: '2-digit',
            year: 'numeric'
        });
    };
    
    // Search functionality for public table
    document.getElementById('searchInput').addEventListener('keyup', function() {
        const searchTerm = this.value.toLowerCase();
        const tableRows = document.querySelectorAll('#cooperationTableBody tr');
        
        tableRows.forEach(row => {
            const namaMitra = row.cells[0].textContent.toLowerCase();
            const lingkup = row.cells[1].textContent.toLowerCase();
            
            if (namaMitra.includes(searchTerm) || lingkup.includes(searchTerm)) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
        
        // Show/hide empty state
        const visibleRows = document.querySelectorAll('#cooperationTableBody tr[style=""], #cooperationTableBody tr:not([style])');
        const emptyState = document.getElementById('emptyState');
        if (visibleRows.length === 0 && searchTerm.length > 0) {
            emptyState.style.display = 'block';
        } else {
            emptyState.style.display = 'none';
        }
    });
</script>
<script src="<?= base_url('js/public/kerjasama/data.js') ?>"></script>
<script src="<?= base_url('js/public/components/table-filter.js') ?>"></script>
<script src="<?= base_url('js/public/kerjasama/data.js') ?>"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Initialize table filter with specific options for Data Kerjasama
    initializeTableFilter('dataKerjasamaTable', {
        searchable: true,
        sortable: true,
        pagination: true,
        itemsPerPage: 10
    });
    
    // Connect existing search box to global filter if exists
    const existingSearch = document.getElementById('global-search');
    const newGlobalSearch = document.getElementById('dataKerjasamaTable-global-search');
    
    if (existingSearch && newGlobalSearch) {
        existingSearch.addEventListener('input', function() {
            newGlobalSearch.value = this.value;
            newGlobalSearch.dispatchEvent(new Event('input'));
        });
        
        const searchBtn = document.querySelector('.kerjasama-search-btn');
        if (searchBtn) {
            searchBtn.addEventListener('click', function() {
                newGlobalSearch.value = existingSearch.value;
                newGlobalSearch.dispatchEvent(new Event('input'));
            });
        }
    }
});
</script>
<?= $this->endSection() ?>