<?= $this->extend('layouts/public') ?>

<?= $this->section('title') ?><?= $page_title ?> - Perpustakaan Nasional RI<?= $this->endSection() ?>

<?= $this->section('description') ?><?= $meta_description ?><?= $this->endSection() ?>

<?= $this->section('keywords') ?>implementasi kerja sama, pelaksanaan mou, realisasi kerjasama, perpustakaan nasional, monitoring<?= $this->endSection() ?>

<?= $this->section('styles') ?>
<link href="<?= base_url('css/public.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/kerjasama/implementasi.css') ?>" rel="stylesheet">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<?= $this->endSection() ?>

<?= $this->section('content') ?>

<!-- Main Content Wrapper -->
<div class="implementasi-wrapper">
    <div class="container">
        
        <!-- Page Header -->
        <div class="implementasi-page-header" data-aos="fade-down">
            <div class="implementasi-header-content">
                <h1 class="implementasi-page-title">Implementasi Kerja Sama</h1>
                <div class="implementasi-breadcrumb">
                    <span>Kerja Sama</span>
                    <span class="separator">/</span>
                    <span class="current">Implementasi Kerja Sama</span>
                </div>
            </div>
        </div>

        <!-- Search Section -->
        <div class="implementasi-search-section" data-aos="fade-up" data-aos-delay="200">
            <div class="implementasi-search-container">
                <div class="implementasi-search-box">
                    <input type="text" 
                           class="implementasi-search-input"
                           id="searchInput" 
                           placeholder="Cari Data"
                           autocomplete="off">
                    <button class="implementasi-search-btn" type="button" id="searchBtn">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Data Table Section -->
        <div class="implementasi-table-section" data-aos="fade-up" data-aos-delay="300">
            <div class="implementasi-table-container">
                <table class="implementasi-table" id="implementasiTable">
                    <thead>
                        <tr>
                            <th class="implementasi-col-partner">Nama Mitra</th>
                            <th class="implementasi-col-period">Masa Berlaku</th>
                            <th class="implementasi-col-implementation">Implementasi Kerja Sama</th>
                            <th class="implementasi-col-scope">Lingkup</th>
                            <th class="implementasi-col-unit">Unit Kerja</th>
                        </tr>
                    </thead>
                    <tbody id="implementasiTableBody">
                        <!-- Data will be loaded here -->
                    </tbody>
                </table>
                
                <!-- Loading State -->
                <div class="implementasi-loading-state" id="loadingState" style="display: none;">
                    <div class="implementasi-loading-spinner">
                        <i class="fas fa-spinner fa-spin"></i>
                    </div>
                    <p>Memuat data implementasi kerja sama...</p>
                </div>
                
                <!-- Empty State -->
                <div class="implementasi-empty-state" id="emptyState" style="display: none;">
                    <div class="implementasi-empty-icon">
                        <i class="fas fa-search"></i>
                    </div>
                    <h4>Tidak ada data ditemukan</h4>
                    <p>Coba ubah kriteria pencarian Anda</p>
                </div>
            </div>
        </div>

        <!-- Pagination Section -->
        <div class="implementasi-pagination-section" data-aos="fade-up" data-aos-delay="400">
            <nav class="pagination-nav" aria-label="Navigation halaman">
                <ul class="implementasi-pagination" id="paginationList">
                    <!-- Pagination will be generated by JavaScript -->
                </ul>
            </nav>
        </div>

    </div>
</div>

<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    // Initialize AOS
    AOS.init({
        duration: 800,
        easing: 'ease-in-out',
        once: true,
        offset: 100
    });
    
    // Pass PHP data to JavaScript
    window.implementasiInitialData = <?= json_encode($implementasi_data ?? []) ?>;
    window.implementasiStats = <?= json_encode($implementasi_stats ?? []) ?>;
    window.filterOptions = <?= json_encode($filter_options ?? []) ?>;
</script>
<script src="<?= base_url('js/public/kerjasama/implementasi.js') ?>"></script>
<?= $this->endSection() ?>