<?= $this->extend('layouts/public') ?>

<?= $this->section('title') ?><?= $page_title ?> - Perpustakaan Nasional RI<?= $this->endSection() ?>

<?= $this->section('description') ?><?= $meta_description ?><?= $this->endSection() ?>

<?= $this->section('keywords') ?>progress kerja sama, perkembangan kerjasama, monitoring kerjasama, perpustakaan nasional<?= $this->endSection() ?>

<?= $this->section('styles') ?>
<link href="<?= base_url('css/public.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/navigation.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/progress_kerjasama.css') ?>" rel="stylesheet">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<?= $this->endSection() ?>

<?= $this->section('content') ?>

<!-- Include Navigation Component -->
<?= $this->include('layouts/components/public_navigation') ?>

<!-- Main Content Wrapper -->
<div class="progress-wrapper">
    <div class="container">
        
        <!-- Page Header -->
        <div class="progress-page-header" data-aos="fade-down">
            <div class="progress-header-content">
                <h1 class="progress-page-title">Progress Kerja Sama</h1>
                <div class="progress-breadcrumb">
                    <span>Kerja Sama</span>
                    <span class="separator">/</span>
                    <span class="current">Progress Kerja Sama</span>
                </div>
            </div>
        </div>

        <!-- Search Section -->
        <div class="progress-search-section" data-aos="fade-up" data-aos-delay="200">
            <div class="progress-search-container">
                <div class="progress-search-box">
                    <input type="text" 
                           class="progress-search-input"
                           id="searchInput" 
                           placeholder="Cari Data"
                           autocomplete="off">
                    <button class="progress-search-btn" type="button" id="searchBtn">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Data Table Section -->
        <div class="progress-table-section" data-aos="fade-up" data-aos-delay="300">
            <div class="progress-table-container">
                <table class="progress-table" id="progressTable">
                    <thead>
                        <tr>
                            <th class="progress-col-date">Tanggal Pengajuan</th>
                            <th class="progress-col-institution">Lembaga</th>
                            <th class="progress-col-type">Jenis</th>
                            <th class="progress-col-progress">Progress</th>
                        </tr>
                    </thead>
                    <tbody id="progressTableBody">
                        <!-- Data will be loaded here -->
                    </tbody>
                </table>
                
                <!-- Loading State -->
                <div class="progress-loading-state" id="loadingState" style="display: none;">
                    <div class="progress-loading-spinner">
                        <i class="fas fa-spinner fa-spin"></i>
                    </div>
                    <p>Memuat data progress kerja sama...</p>
                </div>
                
                <!-- Empty State -->
                <div class="progress-empty-state" id="emptyState" style="display: none;">
                    <div class="progress-empty-icon">
                        <i class="fas fa-search"></i>
                    </div>
                    <h4>Tidak ada data ditemukan</h4>
                    <p>Coba ubah kriteria pencarian Anda</p>
                </div>
            </div>
        </div>

        <!-- Pagination Section -->
        <div class="progress-pagination-section" data-aos="fade-up" data-aos-delay="400">
            <nav class="pagination-nav" aria-label="Navigation halaman">
                <ul class="progress-pagination" id="paginationList">
                    <!-- Pagination will be generated by JavaScript -->
                </ul>
            </nav>
        </div>

    </div>
</div>

<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    // Initialize AOS
    AOS.init({
        duration: 800,
        easing: 'ease-in-out',
        once: true,
        offset: 100
    });
    
    // Pass PHP data to JavaScript
    window.progressInitialData = <?= json_encode($progress_data ?? []) ?>;
    window.progressStats = <?= json_encode($progress_stats ?? []) ?>;
    window.filterOptions = <?= json_encode($filter_options ?? []) ?>;
</script>
<script src="<?= base_url('js/public/progress_kerjasama.js') ?>"></script>
<?= $this->endSection() ?>