<?= $this->extend('layouts/public') ?>

<?= $this->section('title') ?>Peta Kerja Sama<?= $this->endSection() ?>

<?= $this->section('description') ?>Pemetaan lokasi kerjasama perpustakaan di seluruh Indonesia. Visualisasi sebaran mitra kerjasama Perpustakaan Nasional RI dalam pengembangan layanan perpustakaan.<?= $this->endSection() ?>

<?= $this->section('keywords') ?>peta kerjasama, lokasi mitra, sebaran perpustakaan, kerjasama daerah, perpustakaan nasional, indonesia<?= $this->endSection() ?>

<?= $this->section('styles') ?>
<link href="<?= base_url('css/public.css') ?>" rel="stylesheet">
<link href="<?= base_url('css/public/peta_kerjasama.css') ?>" rel="stylesheet">
<?= $this->endSection() ?>

<?= $this->section('content') ?>

<!-- Main Content -->
<section class="peta-section">
    <div class="container">
        <h1 class="page-title text-center">Peta Kerja Sama</h1>
        
        <p class="page-description">
            Visualisasi sebaran kerjasama Perpustakaan Nasional RI dengan berbagai institusi di seluruh Indonesia. 
            Peta ini menunjukkan lokasi mitra kerjasama dalam pengembangan layanan perpustakaan dan literasi.
        </p>

        <!-- Map Section -->
        <div class="map-wrapper">
            <div class="map-container">
                <div id="googleMap" style="width:100%;height:400px;"></div>
                <script>
                    window.petaMarkers = <?= json_encode($markers) ?>;
                </script>
            </div>
        </div>

        <!-- Partner Slider Section -->
        <div class="partner-section">
            <h3 class="partner-title">Mitra Kerjasama</h3>
            
            <div class="partner-slider-container">
                <div class="partner-slider" id="partnerSlider">
                    <?php if (!empty($mitra)): ?>
                        <?php foreach ($mitra as $m): ?>
                            <div class="partner-slide" data-type="<?= esc($m['ruang_lingkup']) ?>">
                                <div class="partner-logo <?= esc($m['ruang_lingkup']) ?>">
                                    <i class="fas fa-book-open"></i>
                                </div>
                                <div class="partner-name"><?= esc($m['nama_mitra']) ?></div>
                                <div class="partner-location">-</div>
                                <div class="partner-type-badge"><?= ucfirst(esc($m['ruang_lingkup'])) ?></div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
            
            <!-- Slider Controls - HANYA INDICATORS -->
            <div class="slider-controls">
                <div class="slider-indicators" id="sliderIndicators">
                    <!-- Indicators will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>
</section>

<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script src="<?= base_url('js/public/peta_kerjasama.js') ?>"></script>
<script>
function initMap() {
    var map = new google.maps.Map(document.getElementById('googleMap'), {
        zoom: 5,
        center: {lat: -2.5489, lng: 118.0149} // Center Indonesia
    });
    if (window.petaMarkers) {
        window.petaMarkers.forEach(function(marker) {
            if(marker.latitude && marker.longitude) {
                new google.maps.Marker({
                    position: {lat: parseFloat(marker.latitude), lng: parseFloat(marker.longitude)},
                    map: map,
                    title: marker.nama_mitra
                });
            }
        });
    }
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap" async defer></script>
<?= $this->endSection() ?>